--INSERT INTO MEMBER (MEMBER_ID, MEMBER_SEQ, MEMBER_NAME) VALUES (1, 10, 'test1'), (1, 20, 'test2');
--INSERT INTO BOARD (BOARD_ID, BOARD_TITLE, MEMBER_ID, MEMBER_SEQ) VALUES (100, '게시판1', 1, 10), (200, '게시판2', 1, 20);
--INSERT INTO COMMENT (COMMENT_ID, COMMENT_TITLE, BOARD_ID) VALUES (1, '코멘트1', 100), (2, '코멘트2', 200);
SELECT 1;